#!/usr/bin/env dash

target_vm='win11'

# extract the state of the VM from virsh
state="$(virsh -c 'qemu:///system' list --all | rg 'win11\s*(\S.*)' -or'$1')"
case "${state}" in

# if the VM is shut off, start VM and open looking glass
'shut off') {
	notify-send "Starting ${target_vm}."
	virsh -c 'qemu:///system' start "${target_vm}"
	looking-glass-client
} ;;

# if the VM is suspended, resume VM and open looking glass
'paused') {
	notify-send "Resuming ${target_vm}."
	looking-glass-client &
	virsh -c 'qemu:///system' resume "${target_vm}"
} ;;

# if the VM is already running:
# - if looking glass is open then suspend the VM and close looking glass
# - otherwise, keep the VM running and re-open looking glass
'running') {
	if pgrep looking-glass; then
		notify-send "Suspending ${target_vm}."
		pkill looking-glass
		virsh -c 'qemu:///system' suspend "${target_vm}"
	else
		looking-glass-client
	fi
} ;;

# send an error message if the state is unknown
*) {
	notify-send "VM ${target_vm} is in an unknown state."
} ;;

esac
